version: "3.7"
services:
  rabbitmq:
    container_name: rabbitmq
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 15672:15672
      - 5672:5672
    hostname: myrabbit
    volumes:
      - /rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@myrabbit
      - /rabbitmq/logs:/var/log/rabbitmq/log
